from main.repositories.ClientRepository import ClientRepository
from main.repositories.WorkerRepository import WorkerRepository
from main.repositories.StoreRepository import StoreRepository
from main.repositories.ItemRepository import ItemRepository
from main.repositories.RoleRepository import RoleRepository
from main.repositories.OperationRepository import OperationRepository
from main.repositories.OperationHistoryRepository import OperationHistoryRepository
from main.repositories.EstimateRepository import EstimateRepository